import type { Profile } from "@/lib/types";
import type { Background, CardDesign, CardElement, ElementType, Keyframe } from "./types";

// Palette mirrors the site (globals.css) so the default card belongs.
export const PALETTE = {
  paper: "#f6f1e6",
  paper2: "#efe6d3",
  ink: "#17140f",
  inkSoft: "#5a5346",
  leaf: "#1fa35a",
  leafDeep: "#0f6a3a",
  tangerine: "#ff5a2c",
  butter: "#ffc63d",
};

let counter = 0;
export function newId(prefix = "el") {
  counter += 1;
  return `${prefix}-${Date.now().toString(36)}-${counter.toString(36)}`;
}

const kf = (at: number, o: Partial<Omit<Keyframe, "at">> = {}): Keyframe => ({
  at,
  x: 0,
  y: 0,
  rotate: 0,
  scale: 1,
  opacity: 1,
  ...o,
});

const solid = (color: string): Background => ({ type: "solid", color, color2: color, angle: 135, image: "" });

/** A fresh element of the given type, centred in a w x h card. */
export function makeElement(type: ElementType, cw: number, ch: number): CardElement {
  const base = { id: newId(type), rotation: 0, opacity: 1, motion: [] as Keyframe[] };
  switch (type) {
    case "text":
      return {
        ...base,
        type,
        name: "Text",
        x: cw / 2 - 200,
        y: ch / 2 - 40,
        w: 400,
        h: 80,
        text_ko: "텍스트",
        text_en: "Text",
        font: "body",
        size: 44,
        weight: 600,
        italic: false,
        color: PALETTE.ink,
        align: "left",
        vAlign: "top",
        letterSpacing: 0,
        lineHeight: 1.15,
        uppercase: false,
      };
    case "shape":
      return {
        ...base,
        type,
        name: "Shape",
        x: cw / 2 - 90,
        y: ch / 2 - 90,
        w: 180,
        h: 180,
        shape: "rect",
        fill: PALETTE.butter,
        stroke: PALETTE.ink,
        strokeWidth: 4,
        radius: 0,
      };
    case "image":
      return {
        ...base,
        type,
        name: "Image",
        x: cw / 2 - 120,
        y: ch / 2 - 120,
        w: 240,
        h: 240,
        src: "",
        fit: "cover",
        radius: 0,
        stroke: PALETTE.ink,
        strokeWidth: 4,
        grayscale: false,
      };
    case "qr":
      return {
        ...base,
        type,
        name: "QR",
        x: cw / 2 - 90,
        y: ch / 2 - 90,
        w: 180,
        h: 180,
        value: "https://www.zanviq.dev",
        color: PALETTE.ink,
        background: "transparent",
      };
  }
}

/**
 * The starting design: front with name + tagline in the site's editorial
 * style, back with contact details and a QR code. `{name}` and `{tagline}`
 * are filled from the profile when rendered.
 */
export function defaultCard(profile: Profile | null): CardDesign {
  const email =
    profile?.links.find((l) => l.url.startsWith("mailto:"))?.url.replace("mailto:", "") || "zanviq.dev@gmail.com";
  const github = profile?.links.find((l) => /github\.com/i.test(l.url))?.url || "https://github.com/Zanviq";
  const W = 1050;
  const H = 600;
  return {
    version: 1,
    width: W,
    height: H,
    radius: 26,
    borderWidth: 5,
    borderColor: PALETTE.ink,
    shadow: { x: 16, y: 16, color: PALETTE.ink },
    scroll: {
      length: 2.4,
      flip: true,
      flipStart: 0.38,
      flipEnd: 0.62,
      tilt: 10,
      scaleFrom: 0.9,
      scaleTo: 1,
      hoverTilt: true,
    },
    front: {
      background: solid(PALETTE.paper),
      elements: [
        {
          id: "front-sun",
          type: "shape",
          name: "Leaf circle",
          shape: "ellipse",
          x: 700,
          y: -160,
          w: 460,
          h: 460,
          rotation: 0,
          opacity: 1,
          fill: "#9fd8b3",
          stroke: PALETTE.ink,
          strokeWidth: 5,
          radius: 0,
          motion: [kf(0), kf(0.4, { x: -70, y: 40, scale: 1.12 })],
        },
        {
          id: "front-tile",
          type: "shape",
          name: "Butter tile",
          shape: "rect",
          x: 850,
          y: 360,
          w: 120,
          h: 120,
          rotation: 12,
          opacity: 1,
          fill: PALETTE.butter,
          stroke: PALETTE.ink,
          strokeWidth: 5,
          radius: 0,
          shadow: { x: 8, y: 8, color: PALETTE.ink },
          motion: [kf(0), kf(0.38, { y: -90, rotate: -40 })],
        },
        {
          id: "front-kicker",
          type: "text",
          name: "Kicker",
          x: 72,
          y: 66,
          w: 600,
          h: 30,
          rotation: 0,
          opacity: 1,
          text_ko: "Portfolio — zanviq.dev",
          text_en: "Portfolio — zanviq.dev",
          font: "mono",
          size: 19,
          weight: 400,
          italic: false,
          color: PALETTE.inkSoft,
          align: "left",
          vAlign: "top",
          letterSpacing: 0.26,
          lineHeight: 1.2,
          uppercase: true,
          motion: [kf(0), kf(0.3, { x: -30, opacity: 0 })],
        },
        {
          id: "front-bar",
          type: "shape",
          name: "Underline",
          shape: "rect",
          x: 74,
          y: 330,
          w: 215,
          h: 26,
          rotation: 0,
          opacity: 1,
          fill: PALETTE.tangerine,
          stroke: "transparent",
          strokeWidth: 0,
          radius: 0,
          motion: [kf(0, { x: -40, opacity: 0 }), kf(0.12), kf(0.34, { x: 40 })],
        },
        {
          id: "front-name",
          type: "text",
          name: "Name",
          x: 66,
          y: 120,
          w: 560,
          h: 260,
          rotation: 0,
          opacity: 1,
          text_ko: "{name}",
          text_en: "{name}",
          font: "display",
          size: 124,
          weight: 600,
          italic: false,
          color: PALETTE.ink,
          align: "left",
          vAlign: "top",
          letterSpacing: -0.02,
          lineHeight: 0.9,
          uppercase: false,
          motion: [kf(0), kf(0.36, { y: -26 })],
        },
        {
          id: "front-tagline",
          type: "text",
          name: "Tagline",
          x: 72,
          y: 408,
          w: 640,
          h: 60,
          rotation: 0,
          opacity: 1,
          text_ko: "{tagline}",
          text_en: "{tagline}",
          font: "display",
          size: 36,
          weight: 400,
          italic: true,
          color: PALETTE.inkSoft,
          align: "left",
          vAlign: "top",
          letterSpacing: 0,
          lineHeight: 1.2,
          uppercase: false,
          motion: [kf(0.05), kf(0.32, { y: 16, opacity: 0.2 })],
        },
        {
          id: "front-role",
          type: "text",
          name: "Role",
          x: 72,
          y: 508,
          w: 640,
          h: 36,
          rotation: 0,
          opacity: 1,
          text_ko: "국민대학교 인공지능학부 · 26학번",
          text_en: "AI · Kookmin University · Class of 2026",
          font: "body",
          size: 22,
          weight: 500,
          italic: false,
          color: PALETTE.ink,
          align: "left",
          vAlign: "top",
          letterSpacing: 0,
          lineHeight: 1.3,
          uppercase: false,
          motion: [],
        },
      ],
    },
    back: {
      background: solid(PALETTE.ink),
      elements: [
        {
          id: "back-name",
          type: "text",
          name: "Name",
          x: 72,
          y: 72,
          w: 560,
          h: 70,
          rotation: 0,
          opacity: 1,
          text_ko: "{name}",
          text_en: "{name}",
          font: "display",
          size: 58,
          weight: 600,
          italic: false,
          color: PALETTE.paper,
          align: "left",
          vAlign: "top",
          letterSpacing: -0.01,
          lineHeight: 1,
          uppercase: false,
          motion: [kf(0.58, { y: 24, opacity: 0 }), kf(0.72)],
        },
        {
          id: "back-rule",
          type: "shape",
          name: "Rule",
          shape: "rect",
          x: 74,
          y: 162,
          w: 90,
          h: 8,
          rotation: 0,
          opacity: 1,
          fill: PALETTE.leaf,
          stroke: "transparent",
          strokeWidth: 0,
          radius: 0,
          motion: [kf(0.6, { x: -30, opacity: 0 }), kf(0.74)],
        },
        ...(
          [
            ["GitHub", github.replace(/^https?:\/\//, ""), github],
            ["Email", email, `mailto:${email}`],
            ["Web", "www.zanviq.dev", "https://www.zanviq.dev"],
          ] as const
        ).flatMap(([label, text, url], i) => [
          {
            id: `back-label-${i}`,
            type: "text" as const,
            name: `${label} label`,
            x: 74,
            y: 232 + i * 86,
            w: 140,
            h: 30,
            rotation: 0,
            opacity: 1,
            text_ko: label,
            text_en: label,
            font: "mono" as const,
            size: 18,
            weight: 400,
            italic: false,
            color: "#9fd8b3",
            align: "left" as const,
            vAlign: "top" as const,
            letterSpacing: 0.2,
            lineHeight: 1.2,
            uppercase: true,
            motion: [kf(0.62 + i * 0.05, { y: 20, opacity: 0 }), kf(0.76 + i * 0.05)],
          },
          {
            id: `back-value-${i}`,
            type: "text" as const,
            name: label,
            x: 74,
            y: 262 + i * 86,
            w: 560,
            h: 40,
            rotation: 0,
            opacity: 1,
            text_ko: text,
            text_en: text,
            font: "body" as const,
            size: 30,
            weight: 600,
            italic: false,
            color: PALETTE.paper,
            align: "left" as const,
            vAlign: "top" as const,
            letterSpacing: 0,
            lineHeight: 1.2,
            uppercase: false,
            link: url,
            motion: [kf(0.62 + i * 0.05, { y: 20, opacity: 0 }), kf(0.76 + i * 0.05)],
          },
        ]),
        {
          id: "back-qr-bg",
          type: "shape",
          name: "QR tile",
          shape: "rect",
          x: 740,
          y: 150,
          w: 240,
          h: 240,
          rotation: 0,
          opacity: 1,
          fill: PALETTE.paper,
          stroke: "transparent",
          strokeWidth: 0,
          radius: 14,
          motion: [kf(0.6, { scale: 0.7, rotate: -8, opacity: 0 }), kf(0.78)],
        },
        {
          id: "back-qr",
          type: "qr",
          name: "QR",
          x: 760,
          y: 170,
          w: 200,
          h: 200,
          rotation: 0,
          opacity: 1,
          value: "https://www.zanviq.dev",
          color: PALETTE.ink,
          background: "transparent",
          link: "https://www.zanviq.dev",
          motion: [kf(0.6, { scale: 0.7, rotate: -8, opacity: 0 }), kf(0.78)],
        },
        {
          id: "back-qr-caption",
          type: "text",
          name: "QR caption",
          x: 740,
          y: 410,
          w: 240,
          h: 30,
          rotation: 0,
          opacity: 1,
          text_ko: "zanviq.dev",
          text_en: "zanviq.dev",
          font: "mono",
          size: 18,
          weight: 400,
          italic: false,
          color: "#bdb6a6",
          align: "center",
          vAlign: "top",
          letterSpacing: 0.1,
          lineHeight: 1.2,
          uppercase: false,
          motion: [kf(0.7, { opacity: 0 }), kf(0.82)],
        },
      ],
    },
  };
}

/** Fill in fields older saves may lack so the renderer never trips. */
export function normalizeCard(raw: unknown, profile: Profile | null): CardDesign {
  const base = defaultCard(profile);
  if (!raw || typeof raw !== "object") return base;
  const c = raw as Partial<CardDesign>;
  const face = (f: unknown, fallback: CardDesign["front"]) => {
    const ff = (f && typeof f === "object" ? f : {}) as Partial<CardDesign["front"]>;
    return {
      background: { ...fallback.background, ...(ff.background ?? {}) },
      elements: Array.isArray(ff.elements)
        ? ff.elements.map((e) => ({ ...e, motion: Array.isArray(e.motion) ? e.motion : [] }))
        : fallback.elements,
    };
  };
  return {
    ...base,
    ...c,
    version: 1,
    shadow: { ...base.shadow, ...(c.shadow ?? {}) },
    scroll: { ...base.scroll, ...(c.scroll ?? {}) },
    front: face(c.front, base.front),
    back: face(c.back, base.back),
  } as CardDesign;
}
